app: restaurant-api
service: restaurant-service

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1
  deploymentBucket:
    name: kielboy8.artifacts
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  deploymentPrefix: serverless


package:
  individually: true

functions:
  test:
    package:
      include:
        - bin/service
    handler: bin/service
    events:
      - http:
          path: restaurant/test
          method: get
          cors: true